exp_cfg:
# one experiment has multiple task, each has a unique task id
# the related files of task id are saved under exp_folder/task_id
  exp_folder: "/home/zby/Programs/Embodied_Analogy/assets/logs/test"
  save_cfg: True
  save_obj_repr: False
  save_result: True

logging:
  level: DEBUG

base_env_cfg:
  offscreen: True
  phy_timestep: 0.004
  use_sapien2: True
  planner_timestep: 0.01

task_cfg:
  task_id: 0
  instruction: "open the cabinet"

obj_env_cfg:
  data_path: "dataset/one_drawer_cabinet/41083_link_3"
  joint_type: "prismatic"
  joint_index: 3
  init_joint_state: 0.24
  active_joint_name: "joint_3"
  active_link_name: "link_3"
  load_scale: 1
  load_pose: [0.8528176546096802, 0.0, 0.5067352652549744]
  load_quat: [0.9986352920532227, 0.01783677004277706, -0.0008765950915403664, -0.0490783266723156]
  obj_description: "cabinet"

algo_cfg:
  use_anygrasp: True

explore_env_cfg:
  record_fps: 30
  pertubation_distance: 0.1
  reserved_distance: 0.05
  valid_thresh: 0.5
  update_sigma: 0.05
  max_tries: 10
  fully_zeroshot: False
  num_initial_pts: 1000

recon_env_cfg:
  num_kframes: 5
  fine_lr: 0.001
  reloc_lr: 0.003

manip_env_cfg:
  manip_type: "open"
  # manip_distance is the abs of manip distance, m for prismatic and degree for revolute
  manip_distance: 0.1
  # max number of manipulations used for closed-loop control
  max_manip: 5
  # for whole traj closed-loop
  prismatic_whole_traj_success_thresh: 0.01
  revolute_whole_traj_success_thresh: 5
  # for intermediate closed-loop
  prismatic_reloc_interval: 0.005
  prismatic_reloc_tolerance: 0.001
  revolute_reloc_interval: 5.0
  revolute_reloc_tolerance: 2.0
  max_attempts: 5
